language: "php"

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - "composer require --dev phpunit/phpunit ^7.0"
  - "composer require --dev phpunit/dbunit"

script:
  - "./vendor/bin/phpunit"
    